namespace: "token-service"
cert_issuer_name: "letsencrypt-prod"
letsencrypt_server_url: "https://acme-v02.api.letsencrypt.org/directory"
ingress_class_name: "nginx"
cert_name: "sahamati-api-tls-sandbox"
cert_issuer_type: "ClusterIssuer"
domain_admin_email: "abhishekg@sanketika.in"
domain: "api.sandbox.sahamati.org.in"
global:
  domain: "api.sandbox.sahamati.org.in"
